name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, release/*]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint pytest

      - name: Lint with pylint
        run: pylint app tests

      - name: Run tests
        run: pytest

      - name: Build package (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload package
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-package
          path: dist/*

